### PR TITLE
Move cassandra into extra project

### PR DESCRIPTION
**Pull request by farodin91**
ToDo
Wait for release of janusgraph 0.5 and update every changes in order for the Janusgraph 0.5

### CODE REVIEW

**Comment by farodin91** [comment]
@mbrukman How can we add the EasyCLA bot into this repo?

**Comment by mbrukman** [comment]
@farodin91 -- done!

**Comment by mbrukman** [comment]
Just to clarify: I added this repo (`JanusGraph/janusgraph-cassandra`) to the EasyCLA config via the lfcla.com website, but I don't know if that's the _only_ step that needs to be done.

@jmertic, can you please let us know what are the full set of steps to onboard a new repo to an existing project? Do we need to set up a webhook manually, or does the addition of the repo take care of all the other steps?

**Comment by jmertic** [comment]
That should be it @mbrukman - the hook is installed at the org level and then permissions are done per repo as you did. Let me know if you see any lingering issues.

**Pull request closed without merging**
